name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cederlys/ubuntu-24.04-asciidoc:install-test-4

    steps:
    - uses: actions/checkout@v6

    - name: Install make
      run: apt-get install -y make

    - name: Run check
      run: make test

    - name: List installed packages
      run: apt list --installed
