name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y asciidoc-base

    - uses: actions/checkout@v6

    - name: Run check
      run: make test
